ktor {
    deployment {
        port = 8081
        host = "0.0.0.0"
    }

    application {
        modules = [com.mad.profile.ApplicationKt.module]
    }

    database {
        localhost = "localhost"
        localhost_port = "5432"

        GATEWAY = "gateway-host"
        GATEWAY_port = "8080"

        mode = "LOCAL"   

        username = "postgres"
        password = "postgres"
        dbName = "postgres"
    }
}
